USE [PIRATES]
GO

/****** Object:  Table [dbo].[CARD_DETAILS]    Script Date: 10/1/2016 2:15:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARD_DETAILS](
	[CARD_NUMBER] [varchar](30) NOT NULL,
	[EMAIL] [varchar](30) NOT NULL,
	[CARD_OWNER] [varchar](30) NOT NULL,
	[CARD_TYPE] [varchar](30) NOT NULL,
	[CVV] [int] NOT NULL,
	[EXPIRY_DATE] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CARD_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CARD_DETAILS]  WITH CHECK ADD FOREIGN KEY([EMAIL])
REFERENCES [dbo].[USERS] ([EMAIL])
GO

ALTER TABLE [dbo].[CARD_DETAILS]  WITH CHECK ADD CHECK  (([CARD_TYPE]='DEBIT' OR [CARD_TYPE]='CREDIT'))
GO

