USE PIRATES
GO


INSERT INTO SHIPPING(EMAIL,SHIPPING_ADDRESS,SHIPPING_TYPE,SHIPPING_CHARGE)
VALUES ('DIA@GMAIL.COM','XYZ','FAST',5)

GO



INSERT INTO SHIPPING(EMAIL,SHIPPING_ADDRESS,SHIPPING_TYPE,SHIPPING_CHARGE)
VALUES ('DIA@GMAIL.COM','LMNO','NORMAL',3)

GO

SELECT * FROM SHIPPING