USE PIRATES
GO

INSERT INTO ITEMS_list ( EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES ('DIA@GMAIL.COM','J245',1,'ABCD','NORMAL')
GO

INSERT INTO ITEMS_list ( EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES ('MICHILINE@GMAIL.COM','J245',1,'ABCD','NORMAL')
GO

INSERT INTO ITEMS_list ( EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES ('MARK.SMITH@GMAIL.COM','M1124',2,'CA','FAST')
GO

INSERT INTO ITEMS_list ( EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES ('JOHN.SMITH@GMAIL.COM','H987',1,'ABCD','NORMAL')
GO

INSERT INTO ITEMS_list ( EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES ('MICHILINE@GMAIL.COM','K1123',1,'ABCD','NORMAL')
GO




INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('DIA@GMAIL.COM','D0009','2','XYZ','FAST')

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('DIA@GMAIL.COM','M00014','2','BCA','FAST')

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('MARK.SMITH@GMAIL.COM','OP005','1','LMNO','NORMAL')

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('MARK.SMITH@GMAIL.COM','WP007','1','LMNO','NORMAL')

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('MICHILINE@GMAIL.COM','MI0013','2','XYZ','FAST')

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE) 
VALUES ('MICHILINE@GMAIL.COM','OP006','1','LMNO','NORMAL')







INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('JOHN.SMITH@GMAIL.COM','CA01','1','LMNO','NORMAL')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('JOHN.SMITH@GMAIL.COM','CE01','2','XYZ','FAST')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('n@gmail.com','CE02','1','LMNO','NORMAL')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('e@gmail.com','CO01','1','LMNO','NORMAL')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('e@gmail.com','CO02','1','LMNO','NORMAL')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('JOHN.SMITH@GMAIL.COM','G01','1','LMNO','NORMAL')

GO

INSERT INTO ITEMS_LIST (EMAIL,ITEM_ID,QUANTITY,SHIPPING_ADDRESS,SHIPPING_TYPE)
VALUES('n@gmail.com','G02','1','LMNO','NORMAL')

GO










SELECT * FROM ITEMS;
SELECT * FROM SELLER
SELECT * FROM USERS;
SELECT * FROM ITEMS_LIST;
