USE PIRATES
GO


INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('W1123','25.00','WOMEN_TOPS','WOMEN',10,'9/25/2016','10/01/2016','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('W1124','20.00','WOMEN_BOTTOM','WOMEN',15,'9/20/2016','10/01/2016','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('M1123','15.20','MEN_TOPS','MEN',5,'7/28/2016','10/28/2016','JOHN@GMAIL.COM')

GO


INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('M1124','10.00','MEN_BOTTOM','MEN',5,'7/25/2016','10/25/2016','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,SELLER_EMAIL)
VALUES ('K1123','13.99','KIDS_TOPS','KIDS','JOHN@GMAIL.COM')

GO


INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,SELLER_EMAIL)
VALUES ('K1124','8.99','KIDS_BOTTOM','KIDS','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('J369','36.00','CHAIN','JEWELLERY',30,'05/02/2016','9/30/2016','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,SELLER_EMAIL)
VALUES ('J245','99.36','NECKLACE','JEWELLERY','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES ('B369','35.99','CREAM_BIG','BEAUTY',30,'05/02/2016','9/30/2016','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,SELLER_EMAIL)
VALUES ('H857','12.00','COTTON','HEALTH','JOHN@GMAIL.COM')

GO

INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,SELLER_EMAIL)
VALUES ('H987','5.99','ANTISEPTIC CREAM','HEALTH','JOHN@GMAIL.COM')

GO








INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('AP004','300.0','WHIRLPOOL','REFRIGERATOR','50','9/1/2016','9/30/2016','ROCK@GMAIL.COM')

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('BP004','301.0','SAMSUNG','REFRIGERATOR','50','9/26/2016','10/1/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('OP005','131.0','WHIRLPOOL','OVEN','60','9/1/2016','9/30/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('OP006','132.0','SAMSUNG','OVEN','60','9/26/2016','10/1/2016','ROCK@GMAIL.COM')

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('WP007','600.0','WHIRLPOOL','WASHER','30','9/1/2016','9/30/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('WP008','300.0','SAMSUNG','WASHER','50','9/26/2016','10/1/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('D0009','200.0','WHIRLPOOL','DRYER','50','9/1/2016','9/30/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('D0010','220.0','SAMSUNG','DRYER','45','9/26/2016','10/1/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('DI0011','150.0','WHIRLPOOL','DISHWASHER','23','9/1/2016','9/30/2016','ROCK@GMAIL.COM')
INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('DI0012','175.0','SAMSUNG','DISHWASHER','12','9/26/2016','10/1/2016','ROCK@GMAIL.COM')

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('MI0013','75.0','SAMSUNG','MUSIC','12','9/26/2016','10/1/2016','ROCK@GMAIL.COM')

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('MI0014','95.0','SONY','MUSIC','22','9/1/2016','9/30/2016','ROCK@GMAIL.COM')


INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('M00013','5.0','HOLLYWOOD','MOVIES','2','9/26/2016','10/1/2016','ROCK@GMAIL.COM')

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL) 
VALUES('M00014','15.0','STUDIOUS','MOVIES','10','9/1/2016','9/30/2016','ROCK@GMAIL.COM')
GO






INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('G01','55.5','NFS','GAMES','10','09/25/2016','10/01/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('G02','45.5','HITMAN','GAMES','02','09/25/2016','10/01/2016','V@GMAIL.COM')
GO


INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CE01','999.9','IPHONE','CELL PHONES','99','09/25/2016','10/01/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CE02','489.9','SAMSUNG','CELL PHONES','120','09/01/2016','09/10/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CA01','2499.9','NIKON','CAMERA','200','09/11/2016','09/17/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CA02','1799.99','SONY','CAMERA','300','09/18/2016','09/24/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CO01','239.99','DELL','COMPUTERS','20','09/24/2016','10/08/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('CO02','1999.99','MAC','COMPUTERS','200','09/24/2016','10/08/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('P0','549.99','UBL','PORTABLE AUDIO','29','09/17/2016','10/11/2016','V@GMAIL.COM')
GO

INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('T01','2799.99','SONY','TV','29','09/13/2016','10/15/2016','V@GMAIL.COM')
GO


INSERT INTO ITEMS (ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES('T02','1422.99','SAMSUNG','TV','2','09/24/2016','10/23/2016','V@GMAIL.COM')
GO

