USE PIRATES
GO

INSERT INTO SELLER (PASSWORD,EMAIL, COMPANY_NAME,USER_NAME, MOBILE_NO) 
VALUES ('004','ROCK@GMAIL.COM','R','STONE','9998887771')
GO

INSERT INTO SELLER (PASSWORD,EMAIL, COMPANY_NAME,USER_NAME, MOBILE_NO) 
VALUES ('001','JOHN@GMAIL.COM','JOHN','MACDONALD','6641233211')
GO

INSERT INTO SELLER (PASSWORD,EMAIL, COMPANY_NAME,USER_NAME, MOBILE_NO) 
VALUES ('007','V@GMAIL.COM','V','R','9123456789')
GO

INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME, MOBILE_NO) 
VALUES ('005','JOHN.SMITH@GMAIL.COM','JOHN','SMITH','9998887772')
GO

INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME) 
VALUES ('006','MICHILINE@GMAIL.COM','MICHILINE','ANN')
GO


INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME, MOBILE_NO) 
VALUES ('002','MARK.SMITH@GMAIL.COM','MARK','ANTONY','5642138971')
GO

INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME) 
VALUES ('003','DIA@GMAIL.COM','DIA','DIANA')
GO


INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME, MOBILE_NO) 
VALUES ('008','E@GMAIL.COM','E','E','922346789')
GO

INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME,MOBILE_NO) 
VALUES ('009','N@GMAIL.COM','N','D','9323456789')
GO

SELECT * FROM USERS
GO