USE [PIRATES]
GO

/****** Object:  Table [dbo].[ITEMS_LIST]    Script Date: 9/26/2016 4:01:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [dbo].[ITEMS_LIST](
	[LIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL] [VARCHAR](30) NOT NULL,
	[ITEM_ID] [VARCHAR](30) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[SHIPPING_ADDRESS] [VARCHAR](50) NOT NULL,
	[SHIPPING_TYPE] [VARCHAR](10) NOT NULL CHECK (SHIPPING_TYPE IN('NORMAL','FAST')),
PRIMARY KEY CLUSTERED 
(
	[LIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ITEMS_LIST]  WITH CHECK ADD FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEMS] ([ITEM_ID])
GO

ALTER TABLE [dbo].[ITEMS_LIST]  WITH CHECK ADD FOREIGN KEY([EMAIL])
REFERENCES [dbo].[USERS] ([EMAIL])
GO
