USE [PIRATES]
GO

/****** Object:  Table [dbo].[ITEMS]    Script Date: 10/1/2016 8:09:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ITEMS](
	[ITEM_ID] [varchar](30) NOT NULL,
	[ITEM_PRICE] [float] NOT NULL,
	[ITEM_NAME] [varchar](30) NOT NULL,
	[ITEM_CATEGORY] [varchar](30) NOT NULL,
	[ITEM_OFFER] [int] NULL,
	[ITEM_OFFER_START_DATE] [date] NULL,
	[ITEM_OFFER_END_DATE] [date] NULL,
	[SELLER_EMAIL] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ITEMS]  WITH CHECK ADD FOREIGN KEY([SELLER_EMAIL])
REFERENCES [dbo].[SELLER] ([EMAIL])
GO

ALTER TABLE [dbo].[ITEMS]  WITH CHECK ADD CHECK  (([ITEM_CATEGORY]='HEALTH' OR [ITEM_CATEGORY]='BEAUTY' OR [ITEM_CATEGORY]='JEWELLERY' OR [ITEM_CATEGORY]='KIDS' OR [ITEM_CATEGORY]='MEN' OR [ITEM_CATEGORY]='WOMEN' OR [ITEM_CATEGORY]='TV' OR [ITEM_CATEGORY]='PORTABLE AUDIO' OR [ITEM_CATEGORY]='COMPUTERS' OR [ITEM_CATEGORY]='CAMERA' OR [ITEM_CATEGORY]='CELL PHONES' OR [ITEM_CATEGORY]='GAMES' OR [ITEM_CATEGORY]='MOVIES' OR [ITEM_CATEGORY]='MUSIC' OR [ITEM_CATEGORY]='DISHWASHER' OR [ITEM_CATEGORY]='DRYER' OR [ITEM_CATEGORY]='WASHER' OR [ITEM_CATEGORY]='OVEN' OR [ITEM_CATEGORY]='REFRIGERATOR'))
GO

