USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_CANCEL_LIST]    Script Date: 9/27/2016 2:07:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_CANCEL_LIST]
@EMAIL VARCHAR(30)
AS
BEGIN
DELETE FROM ITEMS_LIST WHERE EMAIL=@EMAIL 
END

GO