USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_WEEKLY_DEALS]    Script Date: 9/27/2016 2:19:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[PIRATES_SP_WEEKLY_DEALS]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_OFFER_END_DATE>=convert(date,getdate()) AND
DATEDIFF(DAY,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE)<=7
END


GO
