USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_OVEN]    Script Date: 9/27/2016 3:05:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_OVEN]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='OVEN'
END


GO
