USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_VIEW_LISTED_ITEMS]    Script Date: 9/27/2016 4:01:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_VIEW_LISTED_ITEMS]
@EMAIL VARCHAR(30)
AS
BEGIN 
SELECT * FROM ITEMS WHERE SELLER_EMAIL=@EMAIL
END
GO

