USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_CAMERA]    Script Date: 9/27/2016 3:01:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_CAMERA]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='CAMERA'
END

GO

