USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_MUSIC_MOVIES_AND_GAMES_OLD]    Script Date: 9/27/2016 3:05:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_MUSIC_MOVIES_AND_GAMES_OLD]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='MUSIC' OR ITEM_CATEGORY='MOVIES' OR ITEM_CATEGORY='GAMES'
ORDER BY ITEM_OFFER_START_DATE DESC
END

GO

