USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_JEWELLERY]    Script Date: 9/27/2016 3:03:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_JEWELLERY]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='JEWELLERY'
END

GO

