USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_CREATE_USER_SELLER]    Script Date: 9/27/2016 3:11:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PRIATES_SP_CREATE_USER_SELLER]
@PASSWORD VARCHAR(12),
@EMAIL VARCHAR(30),
@COMPANY_NAME VARCHAR(30),
@USER_NAME VARCHAR(30),
@MOBILE_NO VARCHAR(10)
AS
BEGIN 
INSERT INTO SELLER (PASSWORD,EMAIL,COMPANY_NAME,USER_NAME, MOBILE_NO) 
VALUES (@PASSWORD,@EMAIL,@COMPANY_NAME,@USER_NAME,@MOBILE_NO)
END
GO
