USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_WASHER_AND_DRYER]    Script Date: 9/27/2016 3:06:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_WASHER_AND_DRYER]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='WASHER' OR ITEM_CATEGORY='DRYER'
END

GO