USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_MONTHLY_DEALS]    Script Date: 9/27/2016 2:20:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_MONTHLY_DEALS]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_OFFER_END_DATE>=convert(date,getdate()) AND
DATEDIFF(DAY,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE)<=30
END


GO
