USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_REFRIGERATOR]    Script Date: 9/27/2016 3:06:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_REFRIGERATOR]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='REFRIGERATOR'
END


GO
