USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_MEN]    Script Date: 9/27/2016 3:04:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_MEN]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='MEN'
END

GO

