USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_ADD_ITEM_TO_LIST_SELLER]    Script Date: 9/27/2016 3:51:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_ADD_ITEM_TO_LIST_SELLER]
@ITEM_ID VARCHAR(30),
@ITEM_PRICE float,
@ITEM_NAME varchar(30),
@ITEM_CATEGORY varchar(30),
@ITEM_OFFER INT=NULL,
@ITEM_OFFER_START_DATE date=NULL,
@ITEM_OFFER_END_DATE date=NULL,
@SELLER_EMAIL VARCHAR(30)
AS
BEGIN 
INSERT INTO ITEMS ( ITEM_ID,ITEM_PRICE,ITEM_NAME,ITEM_CATEGORY,ITEM_OFFER,ITEM_OFFER_START_DATE,ITEM_OFFER_END_DATE,SELLER_EMAIL)
VALUES (@ITEM_ID,@ITEM_PRICE,@ITEM_NAME,@ITEM_CATEGORY,@ITEM_OFFER,@ITEM_OFFER_START_DATE,@ITEM_OFFER_END_DATE,@SELLER_EMAIL)
END


GO
