USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_CREATE_USER_CUSTOMER]    Script Date: 9/27/2016 3:11:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_CREATE_USER_CUSTOMER]
@PASSWORD VARCHAR(12),
@EMAIL VARCHAR(30),
@FIRST_NAME VARCHAR(30),
@LAST_NAME VARCHAR(30),
@MOBILE_NO VARCHAR(10)=NULL
AS
BEGIN 
INSERT INTO USERS (PASSWORD,EMAIL, FIRST_NAME,LAST_NAME, MOBILE_NO) 
VALUES (@PASSWORD,@EMAIL,@FIRST_NAME,@LAST_NAME,@MOBILE_NO)
OPTION(RECOMPILE)
END

GO


