USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_ADD_ITEM_TO_LIST]    Script Date: 9/26/2016 9:44:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_ADD_ITEM_TO_LIST]
@EMAIL VARCHAR(30),
@ITEM_ID VARCHAR(30),
@QUANTITY INT,
@SHIPPING_ADDRESS VARCHAR(50),
@SHIPPING_TYPE VARCHAR(10)
AS
BEGIN 
INSERT INTO ITEMS_LIST(EMAIL, ITEM_ID,QUANTITY,SHIPPING_ADDRESS, SHIPPING_TYPE) 
VALUES (@EMAIL,@ITEM_ID,@QUANTITY,@SHIPPING_ADDRESS,@SHIPPING_TYPE)
END

GO



