USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_CELLPHONES]    Script Date: 9/27/2016 3:01:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_CELLPHONES]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='CELL PHONES'
END

GO

