USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PRIATES_SP_DISHWASHER]    Script Date: 9/27/2016 3:02:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_DISHWASHER]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='DISHWASHER'
END

GO