USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_SELECT_SHIPPING]    Script Date: 10/1/2016 7:45:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_SELECT_SHIPPING]
@EMAIL VARCHAR(30)
AS
BEGIN
SELECT * FROM SHIPPING WHERE EMAIL=@EMAIL
END

GO

