USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_SELLERLOGINCHECK]    Script Date: 9/27/2016 3:00:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[PIRATES_SP_SELLERLOGINCHECK]
@EMAIL VARCHAR(30),
@PASSWORD VARCHAR(12)
AS
BEGIN
IF EXISTS (SELECT * FROM  SELLER WHERE EMAIL=@EMAIL AND PASSWORD=@PASSWORD ) 
PRINT 'LOGIN SUCCESS'  
ELSE IF EXISTS (SELECT * FROM  SELLER WHERE EMAIL=@EMAIL) 
PRINT 'LOGIN FAILED.. INVALID PASSWORD'  
ELSE 
PRINT 'INVALID USER... USER ID DOES NOT EXISTS...' 
RETURN
END

GO
