USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_ADD_SHIPPING]    Script Date: 10/1/2016 7:28:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[PIRATES_SP_ADD_SHIPPING]
@EMAIL VARCHAR(30),
@SHIPPING_ADDRESS VARCHAR(30),
@SHIPPING_TYPE VARCHAR(30),
@SHIPPING_CHARGE INT
AS
BEGIN
INSERT INTO SHIPPING(EMAIL,SHIPPING_ADDRESS,SHIPPING_TYPE,SHIPPING_CHARGE)
VALUES (@EMAIL,@SHIPPING_ADDRESS,@SHIPPING_TYPE,@SHIPPING_CHARGE)
END

GO

