USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_WOMEN]    Script Date: 9/27/2016 3:07:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PIRATES_SP_WOMEN]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='WOMEN'
END

GO

