USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_KIDS]    Script Date: 9/27/2016 3:03:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_KIDS]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='KIDS'
END

GO

