USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_TV]    Script Date: 9/27/2016 3:06:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_TV]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='TV'
END

GO
