USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_BEAUTY_AND_HEATH]    Script Date: 9/27/2016 3:01:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PIRATES_SP_BEAUTY_AND_HEATH]
AS
BEGIN 
SELECT * FROM ITEMS 
WHERE ITEM_CATEGORY='BEAUTY' OR ITEM_CATEGORY='HEALTH'
END

GO
