USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_VIEW_ITEM_ON_LIST]    Script Date: 10/1/2016 6:49:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[PIRATES_SP_VIEW_ITEM_ON_LIST]
@EMAIL VARCHAR(30)
AS
BEGIN 
SELECT * FROM ITEMS_LIST 
WHERE EMAIL=@EMAIL
END

GO

