USE [PIRATES]
GO

/****** Object:  StoredProcedure [dbo].[PIRATES_SP_DELETE_ITEM_ON_LIST]    Script Date: 9/27/2016 6:50:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PIRATES_SP_DELETE_ITEM_ON_LIST]
@EMAIL VARCHAR(30),
@ITEM_ID VARCHAR(30)
AS
BEGIN 
DELETE FROM ITEMS_LIST 
WHERE ITEM_ID=@ITEM_ID AND EMAIL=@EMAIL
END
GO


