USE [PIRATES]
GO

/****** Object:  Table [dbo].[SELLER]    Script Date: 10/1/2016 1:45:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SELLER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PASSWORD] [varchar](12) NOT NULL,
	[EMAIL] [varchar](30) NOT NULL,
	[COMPANY_NAME] [varchar](30) NOT NULL,
	[USER_NAME] [varchar](30) NOT NULL,
	[MOBILE_NO] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

