USE [PIRATES]
GO

/****** Object:  Table [dbo].[SHIPPING]    Script Date: 10/1/2016 7:25:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SHIPPING](
	[EMAIL] [varchar](30) NOT NULL,
	[SHIPPING_ADDRESS] [varchar](30) NOT NULL,
	[SHIPPING_TYPE] [varchar](30) NOT NULL,
	[SHIPPING_CHARGE] [int] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SHIPPING]  WITH CHECK ADD FOREIGN KEY([EMAIL])
REFERENCES [dbo].[USERS] ([EMAIL])
GO

ALTER TABLE [dbo].[SHIPPING]  WITH CHECK ADD CHECK  (([SHIPPING_TYPE]='NORMAL' OR [SHIPPING_TYPE]='FAST'))
GO

